# Generated by Django 2.0 on 2017-12-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
