
OPEN = "OPEN"
WIRE = "WIRE"
OP1 = "RLOW"
OP2 = "RHIGH"

FUNCTION_KEYS = [OP1, OPEN, OP2, WIRE]
FUNCTION_VALUES = [(0, 0), (0, 1), (1, 0), (1, 1)]

FUNCTION_DICT = {}
for i in range(4):
    FUNCTION_DICT[FUNCTION_KEYS[i]] = FUNCTION_VALUES[i]
