
OPEN = "OPEN"
WIRE = "WIRE"
OP1 = "OPTION1"
OP2 = "OPTION2"

FUNCTION_KEYS = [OPEN, WIRE, OP1, OP2]
FUNCTION_VALUES = [(0, 0), (0, 1), (1, 0), (1, 1)]

FUNCTION_DICT = {}
for i in range(4):
    FUNCTION_DICT[FUNCTION_KEYS[i]] = FUNCTION_VALUES[i]
